<?php
session_start();
include("config/db.php");
$message = '';
if (!isset($_SESSION['user_id']) || $_SESSION['role'] != 'parent') {
    header("Location: login.php");
    exit;
}

$parent_id = $_SESSION['user_id'];

$user_sql = "SELECT * FROM users WHERE id='$parent_id'";
$user_result = mysqli_query($conn, $user_sql);
$user = mysqli_fetch_assoc($user_result);

$child_name = $user['child_name'] ?? '';
$class = $user['child_class'] ?? '';
$roll_no = $user['child_roll_no'] ?? '';

$student_sql = "SELECT * FROM students WHERE name='$child_name' AND class='$class' AND roll_no='$roll_no' LIMIT 1";
$student_result = mysqli_query($conn, $student_sql);

if (mysqli_num_rows($student_result) == 0) {
    $student = null;
    $message = "Your child’s data is not present in the system. Please check your details or contact school administration.";
} else {
    $student = mysqli_fetch_assoc($student_result);
    $student_id = $student['id'];

    $subjects = ['Math','Science','Social','English','Nepali'];
    $resultsData = [];
    $feedback = [];
    $monthlyAttendance = [];
    $dailyAttendance = [];
    $totalSchoolDays = 0;
    $totalPresentDays = 0;
    $currentMonth = date('Y-m');

    $totalMarks = 0;
    $resultsComplete = true;
    foreach ($subjects as $sub) {
        $r = mysqli_query($conn,"SELECT marks FROM results WHERE student_id='$student_id' AND subject='$sub'");
        $row = mysqli_fetch_assoc($r);
        if ($row && $row['marks'] !== null) {
            $mark = $row['marks'];
        } else {
            $mark = 0;
            $resultsComplete = false;
        }
        $resultsData[$sub] = $mark;
        $totalMarks += $mark;
    }
    $percentage = $resultsComplete ? round(($totalMarks/500)*100,2) : 0;

    if ($resultsComplete) {
        foreach ($subjects as $s) {
            if ($resultsData[$s] >= 85)
                $feedback[] = "Excellent performance in $s, showing strong understanding of concepts.";
            elseif ($resultsData[$s] >= 70)
                $feedback[] = "Good performance in $s, but some improvements can be made.";
            elseif ($resultsData[$s] >= 50)
                $feedback[] = "Average performance in $s; needs more practice and focus.";
            else
                $feedback[] = "Critical improvement required in $s; extra support recommended.";
        }
    }

    $ma = mysqli_query($conn,"SELECT * FROM attendance_monthly WHERE student_id='$student_id' ORDER BY month DESC");
    while($m=mysqli_fetch_assoc($ma)){
        $monthlyAttendance[$m['month']] = $m;
        $totalSchoolDays += $m['total_days'];
        $totalPresentDays += $m['present_days'];
    }

    $da = mysqli_query($conn,"SELECT * FROM attendance WHERE student_id='$student_id' AND DATE_FORMAT(date,'%Y-%m')='$currentMonth' ORDER BY date DESC");
    while($d=mysqli_fetch_assoc($da)) $dailyAttendance[] = $d;

    $attendanceComplete = !empty($monthlyAttendance);
    $attendancePercent = $totalSchoolDays ? round(($totalPresentDays/$totalSchoolDays)*100,2) : 0;

    if ($attendancePercent >= 95)
        $feedback[] = "Excellent attendance, demonstrating strong discipline and commitment.";
    elseif ($attendancePercent >= 80)
        $feedback[] = "Good attendance, but some absences noted. Aim for consistency.";
    else
        $feedback[] = "Low attendance; may impact academic progress. Regular attendance recommended.";

    $feedback[] = "This report is automatically generated by the Student Information System.";
}

if (isset($_GET['download_pdf']) && $student) {
    require('fpdf.php');
    $pdf = new FPDF();
    $pdf->AddPage();

    $pdf->SetFont('Arial','B',16);
    $pdf->Cell(0,10,'Student Performance Report',0,1,'C');
    $pdf->Ln(5);

    $pdf->SetFont('Arial','',12);
    $pdf->Cell(0,8,"Name: {$student['name']}",0,1);
    $pdf->Cell(0,8,"Class: {$student['class']}  Roll: {$student['roll_no']}",0,1);
    $pdf->Ln(5);


    $pdf->SetFont('Arial','B',12);
    $pdf->Cell(0,8,"Subject-wise Results",0,1);
    $pdf->SetFont('Arial','',11);
    foreach ($resultsData as $sub=>$mark) {
        $pdf->Cell(0,7,"$sub : $mark",0,1);
    }
    $pdf->Ln(3);
    $pdf->Cell(0,7,"Total: $totalMarks   Percentage: $percentage%",0,1);
    $pdf->Ln(5);

    $pdf->SetFont('Arial','B',12);
    $pdf->Cell(0,8,"Monthly Attendance",0,1);
    $pdf->SetFont('Arial','',11);
    $pdf->Cell(40,7,"Month",1);
    $pdf->Cell(30,7,"Total",1);
    $pdf->Cell(30,7,"Present",1);
    $pdf->Cell(30,7,"Absent",1);
    $pdf->Ln();
    foreach($monthlyAttendance as $m=>$v){
        $pdf->Cell(40,7,$m,1);
        $pdf->Cell(30,7,$v['total_days'],1);
        $pdf->Cell(30,7,$v['present_days'],1);
        $pdf->Cell(30,7,$v['total_days']-$v['present_days'],1);
        $pdf->Ln();
    }
    $pdf->Ln(5);

    $pdf->SetFont('Arial','B',12);
    $pdf->Cell(0,8,"Daily Attendance ($currentMonth)",0,1);
    $pdf->SetFont('Arial','',11);
    $pdf->Cell(40,7,"Date",1);
    $pdf->Cell(40,7,"Status",1);
    $pdf->Ln();
    foreach($dailyAttendance as $d){
        $pdf->Cell(40,7,$d['date'],1);
        if($d['status']=='Absent'){
            $pdf->SetTextColor(211,47,47);
            $pdf->Cell(40,7,$d['status'],1);
            $pdf->SetTextColor(0,0,0);
        }else{
            $pdf->Cell(40,7,$d['status'],1);
        }
        $pdf->Ln();
    }
    $pdf->Ln(5);

    $pdf->SetFont('Arial','B',12);
    $pdf->Cell(0,8,"Feedback",0,1);
    $pdf->SetFont('Arial','',11);
    foreach ($feedback as $f) {
        $pdf->MultiCell(0,6,"- $f");
    }

    $pdf->Output("D", "Student_Report_{$student['name']}.pdf");
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Parent Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
body {
    background: linear-gradient(135deg, #f0f2f5, #e3e6eb);
    font-family: Arial, sans-serif;
    margin: 0;
}

.container {
    max-width: 1400px;
    margin: auto;
    padding: 40px;
}

h1,
h2,
h3 {
    color: #d32f2f;
}

.card {
    background: #fff;
    padding: 25px;
    border-radius: 12px;
    box-shadow: 0 6px 18px rgba(0, 0, 0, 0.12);
    margin-bottom: 25px;
}

.stats-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 20px;
}

.stat-box {
    background: #fdecea;
    padding: 20px;
    border-radius: 10px;
    text-align: center;
    font-weight: bold;
}

table {
    width: 100%;
    border-collapse: collapse;
}

th,
td {
    padding: 10px;
    border-bottom: 1px solid #ddd;
    text-align: center;
}

th {
    background: #f5f5f5;
}

.fail {
    color: #d32f2f;
    font-weight: bold;
}

.charts-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 25px;
}

.chart-box {
    height: 350px;
}

canvas {
    width: 100% !important;
    height: 260px !important;
}

.scrollable {
    max-height: 300px;
    overflow-y: auto;
}

.alert {
    color: #d32f2f;
    font-weight: bold;
    text-align: center;
}

@media (max-width: 900px) {
    .stats-grid,
    .charts-grid {
        grid-template-columns: 1fr;
    }
}

.download-btn {
    display: inline-block;
    margin: 20px 0;
    padding: 10px 20px;
    background: #d32f2f;
    color: #fff;
    text-decoration: none;
    border-radius: 6px;
}

.download-btn:hover {
    background: #b71c1c;
}
</style>

</head>
<body>

<div class="container">
<h1>Welcome, Parent!</h1>

<?php if($message): ?><div class="alert"><?= $message ?></div><?php endif; ?>

<?php if($student): ?>
<a href="?download_pdf=1" class="download-btn">⬇ Download PDF</a>

<div class="card">
<h3><?= $student['name'] ?> (Roll <?= $student['roll_no'] ?>)</h3>
<div class="stats-grid">
<div class="stat-box">School Days<br><?= $totalSchoolDays ?></div>
<div class="stat-box">Present Days<br><?= $totalPresentDays ?></div>
<div class="stat-box">Attendance <br><?= $attendancePercent ?>%</div>
<div class="stat-box">Result <br><?= $resultsComplete?$percentage.'%':'N/A' ?></div>
</div>
</div>

<?php if($resultsComplete): ?>
<div class="card">
<h3>Subject-wise Results</h3>
<table>
<tr><?php foreach($subjects as $s): ?><th><?= $s ?></th><?php endforeach; ?><th>Total</th><th>%</th></tr>
<tr><?php foreach($subjects as $s): ?>
<td class="<?= ($resultsData[$s]<40)?'fail':'' ?>"><?= $resultsData[$s] ?></td>
<?php endforeach; ?>
<td><?= $totalMarks ?></td>
<td><?= $percentage ?>%</td>
</tr>
</table>
</div>
<?php endif; ?>

<div class="card scrollable">
<h3>Monthly Attendance</h3>
<table>
<tr><th>Month</th><th>Total</th><th>Present</th><th>Absent</th></tr>
<?php foreach($monthlyAttendance as $m=>$v): ?>
<tr>
<td><?= $m ?></td>
<td><?= $v['total_days'] ?></td>
<td><?= $v['present_days'] ?></td>
<td><?= $v['total_days']-$v['present_days'] ?></td>
</tr>
<?php endforeach; ?>
</table>
</div>

<div class="card scrollable">
<h3>Daily Attendance (<?= $currentMonth ?>)</h3>
<table>
<tr><th>Date</th><th>Status</th></tr>
<?php foreach($dailyAttendance as $d): ?>
<tr>
<td><?= $d['date'] ?></td>
<td class="<?= ($d['status']=='Absent')?'fail':'' ?>"><?= $d['status'] ?></td>
</tr>
<?php endforeach; ?>
</table>
</div>

<div class="charts-grid">
<div class="card chart-box">
<h3>Marks Chart</h3>
<canvas id="marksChart"></canvas>
</div>
<div class="card chart-box">
<h3>Attendance Chart</h3>
<canvas id="attendanceChart"></canvas>
</div>
</div>

<?php if(!empty($feedback)): ?>
<div class="card">
<h3>Feedback</h3>
<ul><?php foreach($feedback as $f): ?><li><?= htmlspecialchars($f) ?></li><?php endforeach; ?></ul>
</div>
<?php endif; ?>

<?php endif; ?>
</div>

<script>
<?php if($resultsComplete): ?>
new Chart(marksChart,{
 type:'bar',
 data:{labels:<?= json_encode($subjects) ?>,
 datasets:[{data:<?= json_encode(array_values($resultsData)) ?>,backgroundColor:'#d32f2f'}]},
 options:{maintainAspectRatio:false,scales:{y:{beginAtZero:true,max:100}}}
});
<?php endif; ?>

<?php if($attendanceComplete && !empty($monthlyAttendance)):
$last=array_values($monthlyAttendance)[0];
$abs=$last['total_days']-$last['present_days'];
?>
new Chart(attendanceChart,{
 type:'pie',
 data:{labels:['Present','Absent'],
 datasets:[{data:[<?= $last['present_days'] ?>,<?= $abs ?>],
 backgroundColor:['#388e3c','#d32f2f']}]},
 options:{maintainAspectRatio:false}
});
<?php endif; ?>
</script>

</body>
</html>
